
[x-axis]
where = top

#[Jurkat WT]
#title = Jurkat WT
#file = ./GSE206131_Jurkat_WT_microC.mcool::/resolutions/2000
#colormap = ['white', (1, 0.88, .66), (1, 0.74, 0.25), (1, 0.5, 0), (1, 0.19, 0), (0.74, 0, 0), (0.35, 0, 0)]
#depth = 500000
#max_value = 0.008
#file_type = hic_matrix
#fontsize = 15

#[spacer]

[Jurkat WT H3K27me3]
file = ./merged_bigwigs/normalized_to_IgG/WT_me3_log2.bigwig
color = black
height = 2.5
title = Jurkat WT H3K27me3
number_of_bins = 600
min_value = 0
max_value = 1 

[spacer]

[Jurkat A7 H3K27me3]
file = ./merged_bigwigs/normalized_to_IgG/A7_me3_log2.bigwig
color = #8B008B
height = 2.5
title = Jurkat A7 H3K27me3
number_of_bins = 600
min_value = 0
max_value = 1

[spacer]

[Jurkat C9 H3K27me3]
file = ./merged_bigwigs/normalized_to_IgG/C9_me3_log2.bigwig
color = #FFA500
height = 2.5
title = Jurkat C9 H3K27me3
number_of_bins = 600
min_value = 0
max_value = 1

[spacer]

[Jurkat WT H2AK119ub]
file = ./merged_bigwigs//normalized_to_IgG/WT_ub_log2.bigwig
color = black
height = 2.5
title = Jurkat WT H2AK119ub
number_of_bins = 800
min_value = 0
max_value = 1

[spacer]

[Jurkat A7 H2AK119ub]
file = ./merged_bigwigs/normalized_to_IgG/A7_ub_log2.bigwig
color = #8B008B
height = 2.5
title = Jurkat A7 H2AK119ub
number_of_bins = 800
min_value = 0
max_value = 1

[spacer]

[Jurkat C9 H2AK119ub]
file = ./merged_bigwigs/normalized_to_IgG/C9_ub_log2.bigwig
color = #FFA500
height = 2.5
title = Jurkat C9 H2AK119ub
number_of_bins = 800
min_value = 0
max_value = 1

[spacer]

[Jurkat WT H3K27ac]
file = ./merged_bigwigs/normalized_to_IgG/WT_ac_log2.bigwig
color = black
height = 2.5
title = Jurkat WT H3K27ac
number_of_bins = 800
min_value = 0
max_value = 1

[spacer]

[Jurkat A7 H3K27ac]
file = ./merged_bigwigs/normalized_to_IgG/A7_ac_log2.bigwig
color = #8B008B
height = 2.5
title = Jurkat A7 H3K27ac
number_of_bins = 800
min_value = 0
max_value = 1

[spacer]

[Jurkat C9 H3K27ac]
file = ./merged_bigwigs/normalized_to_IgG/C9_ac_log2.bigwig
color = #FFA500
height = 2.5
title = Jurkat C9 H3K27ac
number_of_bins = 800
min_value = 0
max_value = 1


[spacer]

[Jurkat WT Myb]
file = ./public_datasets/ChIPseq/Myb_ChIPseq/GSM4420242_TL-1-PJ-Myb_S6.bcov.hg38.sort.split.bw
color = black
height = 2.5
title = Jurkat WT MYB ChIP-Seq
number_of_bins = 600
min_value = 0
max_value = 2

    
[Jurkat A7 Myb]
file = ./public_datasets/ChIPseq/Myb_ChIPseq/GSM4420243_TL-1-EZH2-Myb_S2.bcov.hg38.sort.split.bw
color = #8B008B
height = 2.5
title = Jurkat A7 MYB ChIP-Seq
number_of_bins = 600
min_value = 0
max_value = 2

    
[spacer]

[WT ATAC NRFs]
file = ./ATAC-peaks/open_fragments/WT.open.fragments.bigwig
color = black
height = 2.5
title = WT ATAC NFRs
number_of_bins = 800
min_value = 0
max_value = 50
file_type = bigwig    

[spacer]

[A7 ATAC NRFs]
file = ./ATAC-peaks/open_fragments/A7.open.fragments.bigwig
color = #8B008B
height = 2.5
title = A7 ATAC NFRs
number_of_bins = 800
min_value = 0
max_value = 50
file_type = bigwig

[spacer]
    
[C9 ATAC NRFs]
file = ./ATAC-peaks/open_fragments/C9.open.fragments.bigwig
color = #FFA500
height = 2.5
title = C9 ATAC NFRs
number_of_bins = 800
min_value = 0
max_value = 50
file_type = bigwig
  
[spacer]
  
[Genes]
file = ./genome_files/hg38-refGene.gtf
height = 5
prefered_name = gene_id
merge_transcripts = true
max_labels = 200
title = Genes
fontsize = 15
merge_overlapping_exons = true
file_type = gtf
gene_rows = 6
